name: Heroku Deployment

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.NBASTARS}}
          heroku_email: ${{secrets.NBASTARSEMAIL}}
          heroku_app_name: ${{secrets.NBASTARSAPI}}
